[workspace]
members = ["libwaj"]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Matthieu Gautier <mgautier@kymeria.fr>"]
repository = "https://framagit.org/jubako/waj"
license = "MIT"

[workspace.dependencies]
jubako = { git = "https://framagit.org/jubako/jubako.git" }

[package]
name = "waj"
description = "Store a web site in a package"
categories = ["command-line-utilities", "compression"]
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
libwaj = { path = "libwaj", version = "0.1.0" }
jubako.workspace = true
indicatif = "0.17.3"
