[package]
name = "jim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
jubako = "0.1.0"
mime_guess = "2.0.4"
percent-encoding = "2.2.0"
tiny_http = "0.12.0"
